### PR TITLE
Fixing -Werror=format-security errors

### PR DESCRIPTION
**Pull request by Scriptkiddi**

### CODE REVIEW

**Comment by jackkilgore** [comment]
Hello, before we can pull, can you add .c_str() to "ecSource/src/ecInterface.cpp:line 408". The program won't compile as ImGui likes c strings. Thanks for fixing those annoying errors!

**Comment by Scriptkiddi** [comment]
Interesting, what system are you using? On my Linux it compiles. But I will fix it anyway

**Comment by Scriptkiddi** [comment]
done

**Comment by jackkilgore** [comment]
works, thanks! I'm using OSX Mojave with the clang compiler. Your compiler must be smarter than mine and implicitly converts C++ strings to C strings.

**Pull request merged**
